### ISSUE TITLE
Subdirectories

### ISSUE THREAD

**Issue by stan5079** [mrf345/flask_minify#57]
Files placed in subdirectories are ignored.

Example:
Processed: /app/blueprint/static/css/mycss.css
Ignored: /app/blueprint/static/css/ext/extcss.css

Not necessarily an issue, rather an improvement.

**Comment by mrf345** [comment]
I can't reproduce the issue with a vanilla setup, most probably some special condition in your setup

![image](https://user-images.githubusercontent.com/26286907/144719412-a48e02d1-d9c2-44cf-97ab-bfc56f63f8d1.png)

**Comment by stan5079** [comment]
I should've been more clear. This is only happening in blueprints.

**Comment by mrf345** [comment]
No worries, tested with blueprints, seems to work

![image](https://user-images.githubusercontent.com/26286907/144726087-9c716125-f975-4877-8d9c-a45286566f9c.png)

**Comment by stan5079** [comment]
We're not using the same set-up anymore as when I made the ticket. So I'm sorry to have wasted your time. I might come back to this later if I can find the right set-up. Thanks for looking into it!

**Comment by mrf345** [comment]
No worries at all, my pleasure. Let's leave it open for now, someone else might come across the edge-case that caused it.

**Comment by retuow** [comment]
I thought I had the same issue as well, and I spent longer than I wish to admit debugging it. But it was a false alarm. It looked like javascript (stored in `static/js`) was not minified, but it turned out my browser still had a non-minified version cached somewhere. Retrieving the file with `curl`, or a hard refresh in the browser showed the file was actually minified.
