### ISSUE TITLE
Javascript not working after minifying.

### ISSUE THREAD

**Issue by rbcabreraUPM** [mrf345/flask_minify#6]
following the documentation, only the html portion was minified. my javascript code was still the same even setting js =True and my javascript isnt working properly anymore.

**Comment by mrf345** [comment]
The `fail_safe` option is enabled by default, so any exceptions and failures to minify will be silenced. The best way to know what's going wrong, is to get an exception. So start by disabling `fail_safe`, and pasting the exception that you will get here. `minify(app=app, fail_safe=False)` 

And make sure to upgrade to the `0.13` release, since the issue might have been fixed there `pip install --upgrade Flask-Minify`

**Comment by mrf345** [comment]
The `fail_safe` option is enabled by default, so any exceptions and failures to minify will be silenced. The best way to know what's going wrong, is to get an exception. So start by disabling `fail_safe`, and pasting the exception that you will get here. `minify(app=app, fail_safe=False)` 

And make sure to upgrade to the `0.13` release, since the issue might have been fixed there `pip install --upgrade Flask-Minify`

**Comment by PoojaG20** [comment]
At my side also, Javascript is not working properly after setting js=True, and on settign fail_safe=False, its having issues on loading css. Besides that it gives following error -
1)Uncaught SyntaxError: Unexpected token ';'
2) Uncaught SyntaxError: Unexpected token '.'
3) Uncaught SyntaxError: Unexpected token 'else'
These semicons , else statements are added from minify not as per my code. How to fix it, make js working.
